### ISSUE TITLE
Task "Gather information about existing home directories" fails when bootstrap__admin is 'false'

### ISSUE THREAD

**Issue by antoineco** [debops/ansible-bootstrap#34]
#### Environment
```
ansible 2.1.1.0
Debian 8 (jessie) - client + hosts
```

#### Command executed
`debops bootstrap -u admin -i ansible/inventory/internal -b`

#### Output
```
TASK [debops.bootstrap : Gather information about existing home directories] ***
task path: /root/.local/share/debops/debops-playbooks/roles/debops.bootstrap/tasks/admin_accounts.yml:8
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 93, in run
    items = self._get_loop_items()
  File "/usr/lib/python2.7/dist-packages/ansible/executor/task_executor.py", line 191, in _get_loop_items
    loop_terms = listify_lookup_plugin_terms(terms=self._task.loop_args, templar=templar, loader=self._loader, fail_on_undefined=True, convert_bare=True)
  File "/usr/lib/python2.7/dist-packages/ansible/utils/listify.py", line 35, in listify_lookup_plugin_terms
    terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 330, in template
    result = self._do_template(variable, preserve_trailing_newlines=preserve_trailing_newlines, escape_backslashes=escape_backslashes, fail_on_undefined=fail_on_undefined, overrides=overrides)
  File "/usr/lib/python2.7/dist-packages/ansible/template/__init__.py", line 494, in _do_template
    res = j2_concat(rf)
  File "<template>", line 9, in root
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python2.7/dist-packages/yaml/__init__.py", line 69, in load
    loader = Loader(stream)
  File "/usr/lib/python2.7/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 87, in __init__
    self.determine_encoding()
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 126, in determine_encoding
    self.update_raw()
  File "/usr/lib/python2.7/dist-packages/yaml/reader.py", line 183, in update_raw
    data = self.stream.read(size)
AttributeError: 'list' object has no attribute 'read'

fatal: [ip-172-31-55-149.eu-central-1.compute.internal]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

#### Troubleshooting

1. A debug task placed right before "Manage System Administrator accounts" shows me that `bootstrap__admin` is set to `False`, just like I set in my group_vars, ~~so `admin_accounts.yml` shouldn't be included at all.~~

2. The task "Gather information about existing users" is skipped due to 1., therefore the fact `getent_passwd` is not set:
  ```
  TASK [debops.bootstrap : Gather information about existing users] **************
  task path: /root/.local/share/debops/debops-playbooks/roles/debops.bootstrap/tasks/admin_accounts.yml:3
  skipping: [ip-172-31-55-149.eu-central-1.compute.internal] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
  ```

3. If I comment the task "Manage System Administrator accounts", the play goes through.

**Comment by drybjed** [comment]
Thanks for the heads up, I'll check it out.

**Comment by antoineco** [comment]
Thanks @drybjed !
